"""Constants and allowed parameter values specified in the News API."""
TOP_HEADLINES_URL = "https://newsapi.org/v2/top-headlines"
EVERYTHING_URL = "https://newsapi.org/v2/everything"
SOURCES_URL = "https://newsapi.org/v2/sources"

#: The 2-letter ISO 3166-1 code of the country you want to get headlines for.  If not specified,
#: the results span all countries.
COUNTRIES = {
    "ae",
    "ar",
    "at",
    "au",
    "be",
    "bg",
    "br",
    "ca",
    "ch",
    "cn",
    "co",
    "cu",
    "cz",
    "de",
    "eg",
    "fr",
    "gb",
    "gr",
    "hk",
    "hu",
    "id",
    "ie",
    "il",
    "in",
    "it",
    "jp",
    "kr",
    "lt",
    "lv",
    "ma",
    "mx",
    "my",
    "ng",
    "nl",
    "no",
    "nz",
    "ph",
    "pl",
    "pt",
    "ro",
    "rs",
    "ru",
    "sa",
    "se",
    "sg",
    "si",
    "sk",
    "th",
    "tr",
    "tw",
    "ua",
    "us",
    "ve",
    "za",
}

DEFAULT_LANGUAGES = {
    "ae": "ar",
    "ar": "es",
    "at": "de",
    "au": "en",
    "be": "nl",
    "bg": "bg",
    "br": "pt",
    "ca": "en",
    "ch": "de",
    "cn": "zh",
    "co": "es",
    "cu": "es",
    "cz": "cs",
    "de": "de",
    "eg": "ar",
    "fr": "fr",
    "gb": "en",
    "gr": "el",
    "hk": "zh",
    "hu": "hu",
    "id": "id",
    "ie": "en",
    "il": "he",
    "in": "hi",
    "it": "it",
    "jp": "ja",
    "kr": "ko",
    "lt": "lt",
    "lv": "lv",
    "ma": "ar",
    "mx": "es",
    "my": "ms",
    "ng": "en",
    "nl": "nl",
    "no": "no",
    "nz": "en",
    "ph": "en",
    "pl": "pl",
    "pt": "pt",
    "ro": "ro",
    "rs": "sr",
    "ru": "ru",
    "sa": "ar",
    "se": "sv",
    "sg": "en",
    "si": "sl",
    "sk": "sk",
    "th": "th",
    "tr": "tr",
    "tw": "zh",
    "ua": "uk",
    "us": "en",
    "ve": "es",
    "za": "zu",
}

#: The 2-letter ISO-639-1 code of the language you want to get articles for.  If not specified,
#: the results span all languages.
LANGUAGES = {"ar", "de", "en", "es", "fr", "he", "it", "nl", "no", "pt", "ru", "sv", "ud", "zh"}

#: The category you want to get articles for.  If not specified,
#: the results span all categories.
CATEGORIES = {"business", "entertainment", "general", "health", "science", "sports", "technology"}

#: The order to sort article results in.  If not specified, the default is ``"publishedAt"``.
SORT_METHOD = {"relevancy", "popularity", "publishedAt"}

